-- 1. How many total orders has UrbanCart received so far? 
select 
count (order_id) as total_order
from public."FactOrders"

-- 2. How many unique customers have placed at least one order? 

select 
count(distinct customer_id) as unique_customers
from public."FactOrders";

-- 3. Which cities generate the highest number of orders? 

select
city,
count(order_id) as total_order_per_city
from public."FactOrders" as o
join public."DimCustomers" as c on c.customer_id=o.customer_id::bigint
group by city
order by total_order_per_city desc

-- 4. What percentage of customers have placed more than one order? 

with orders_per_customer as (
    select 
        customer_id,
        count(order_id) as order_per_customer
    from public."FactOrders"
    group by customer_id
)

select
	round(count(*)::numeric/ (select count(distinct customer_id) from public."FactOrders")* 100,2)
	as percentage_repeat_customers
from orders_per_customer
where order_per_customer > 1;

-- 5. What is the monthly trend of total orders over time? 
select
to_char(date_trunc('month', order_date), 'Month') as month,
count(order_id) as total_orders
from public."FactOrders"
group by date_trunc('month', order_date)
order by 2 desc;

-- 6. What is the total revenue generated by UrbanCart? 
with multiply_amount as (
    select 
        fo.order_id,
        fo.product_id,
        fo.quantity,
        p.unit_price,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    left join public."DimProducts" as p 
      on p.product_id = fo.product_id
)
select 
sum(total_amount) as revenue
from multiply_amount;

-- 7. Which product categories contribute the most to total revenue? 

with multiply_amount as (
    select 
        fo.order_id,
        fo.product_id,
        fo.quantity,
        p.unit_price,
		p.category,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    left join public."DimProducts" as p 
      on p.product_id = fo.product_id
)
select 
category,
sum(total_amount) as reveneu_by_category
from "multiply_amount"
group by category

-- 8. Which individual products generate the highest revenue? 

with multiply_amount as (
    select 
        fo.order_id,
        fo.product_id,
        fo.quantity,
        p.unit_price,
		p.product_name,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    left join public."DimProducts" as p 
      on p.product_id = fo.product_id
)
select 
product_name,
sum(total_amount) as reveneu_by_product
from "multiply_amount"
group by 1
order by 2 desc


-- 9. What is the average order value (AOV) and Average Basket Size? 

with multiply_amount as (
    select 
        fo.order_id,
        fo.product_id,
        fo.quantity,
        p.unit_price,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    left join public."DimProducts" as p 
      on p.product_id = fo.product_id
)
select 
round(sum(total_amount)/count(distinct order_id),2) as avg_order_value,
round(sum(quantity)/count(distinct order_id),2) as avg_basket
from multiply_amount

-- 10. Which products are at risk of stock-out due to high sales volume and low inventory? 

with stock_compare as(
select 
    product_name,
	sum(quantity) as Total_order_per_product,
	sum(distinct p.stock) as total_stock
    from public."FactOrderItems" as fo
    left join public."DimProducts" as p 
    on p.product_id = fo.product_id
    group by 1
)
select
*
from stock_compare
-- where Total_order_per_product>total_stock

where Total_order_per_product>total_stock or ((total_stock-Total_order_per_product)<30 and (Total_order_per_product-total_stock)<0)

-- 11. Which customers contribute the highest total revenue? 

with total_revenue as(
	select 
	*,
	(p.unit_price::numeric * fo.quantity::numeric) as total_amount
	from public."FactOrderItems" as fo
	join public."FactOrders" as o on o.order_id=fo.order_id
	join public."DimProducts" as p on p.product_id=fo.product_id
)
	select 
	tr.customer_id,
	full_name,
	sum(total_amount) as customer_per_revenue
	-- rank() over(order by total_amount desc) as ranks
	from total_revenue as tr
	left join public."DimCustomers" as c on c.customer_id=tr.customer_id
	group by 1,2
	order by 3 desc
	limit 3

-- 12. What is the average number of products purchased per order? 
select 
round(sum(quantity)/count(distinct order_id),2) as avg_purchase__per_oder
from public."FactOrderItems"

-- 13. Do male and female customers show different purchasing patterns by category? 

with total_revenue as (
    select 
       *,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    join public."FactOrders" as o on o.order_id = fo.order_id
    join public."DimProducts" as p on p.product_id = fo.product_id
)
select 
    tr.category,
    c."Gender", 
    sum(tr.total_amount) as gender_revenue_per_category
from total_revenue as tr
left join public."DimCustomers" as c on c.customer_id = tr.customer_id
group by tr.category, c."Gender"
order by 1, gender_revenue_per_category desc;

-- 14. Which cities have the highest average order value? 

with total_revenue as (
    select 
       fo.order_id,
	   o.customer_id,
        (p.unit_price::numeric * fo.quantity::numeric) as total_amount
    from public."FactOrderItems" as fo
    join public."FactOrders" as o on o.order_id = fo.order_id
    join public."DimProducts" as p on p.product_id = fo.product_id
)
select
    city,
	round(sum(tr.total_amount)/count(distinct order_id),2) as order_value_per_city
    -- count(distinct order_id) as order_per_city,
    -- sum(tr.total_amount) as revenue_per_city
from total_revenue as tr
left join public."DimCustomers" as c on c.customer_id = tr.customer_id
group by 1
order by order_value_per_city desc;


-- 15. How does customer purchasing behavior change over time since account creation? 

-- 16. Which payment methods are used most frequently? 

select
method,
count(payment_id) as methods
from public."FactPayment"
group by 1
order by 2 desc

-- 17. Is there any relationship between payment method and order status? 

select
method,
status,
count(status) as payments_status
from public."FactPayment" as p
join public."FactOrders" as o on o.order_id=p.order_id
group by 1,2
order by 3 desc


-- 18. Do certain cities prefer specific payment methods? 
select
city,
method,
count(method) as payments_method
from public."FactPayment" as p
join public."FactOrders" as o on o.order_id=p.order_id
join public."DimCustomers" as c on c.customer_id=o.customer_id
group by 1,2
order by 3 desc

-- 19. Are higher-value orders associated with specific payment methods? 

with join_table as (
	select
	p.method,
	p.order_id,
	(po.unit_price::numeric * fo.quantity::numeric) as total_amount
	from public."FactPayment" as p
	join public."FactOrders" as o on o.order_id=p.order_id
	join public."FactOrderItems" as fo on fo.order_id=o.order_id
	join public."DimProducts" as po on po.product_id=fo.product_id
)
select
method,
order_id,
sum(total_amount) as amount_per_order
from join_table
group by 1,2
order by 3 desc
limit 100


-- 20. What is the average number of items per order by payment method? 

with join_table as (
	select
	p.payment_id,
	p.method,
	p.order_id,
	fo.quantity
	from public."FactPayment" as p
	left join public."FactOrderItems" as fo on fo.order_id=p.order_id
)
select
method,
round(sum(quantity)/count(order_id),2) as items_per_method
-- count(order_id) as total_order,
-- sum(quantity) as total_quantity
from join_table
group by 1
order by 2 desc

-- 21. Which products are most frequently ordered together? 

with pair_product as (
	select
	fo1.product_id as product1,
	fo2.product_id as product2,
	count(*) AS times_ordered_together 
	from public."FactOrderItems" as fo1
	join public."FactOrderItems" as fo2 on (fo1.order_id=fo2.order_id and fo1.product_id < fo2.product_id)
	group by 1,2
)
select 
p.product_name,
p1.product_name,
times_ordered_together
from pair_product as pp
join public."DimProducts" as p on p.product_id=pp.product1
join public."DimProducts" as p1 on p1.product_id=pp.product2
order by times_ordered_together desc


-- 22. Which product pairs appear most often across all orders? 

with pair_product as (
	select
	fo1.product_id as product1,
	fo2.product_id as product2,
	count(*) AS times_ordered_together 
	from public."FactOrderItems" as fo1
	join public."FactOrderItems" as fo2 on (fo1.order_id=fo2.order_id and fo1.product_id < fo2.product_id)
	group by 1,2
)
select 
p.product_name,
p1.product_name,
times_ordered_together
from pair_product as pp
join public."DimProducts" as p on p.product_id=pp.product1
join public."DimProducts" as p1 on p1.product_id=pp.product2
order by times_ordered_together desc




-- 23. Are there product pairs that consistently drive higher order values? 
with order_value as (
    select
        o.order_id,
        sum(p.unit_price::numeric * fo.quantity::numeric) as order_total
    from public."FactOrders" o
    join public."FactOrderItems" fo on o.order_id = fo.order_id
    join public."DimProducts" p on p.product_id = fo.product_id
    group by 1
),
product_pairs as (
    select
		fo1.order_id,
        fo1.product_id as product_1_id,
        fo2.product_id as product_2_id
    from public."FactOrderItems" fo1
    join public."FactOrderItems" fo2
        on (fo1.order_id = fo2.order_id
       and fo1.product_id > fo2.product_id)
)
select
    p1.product_name as product_1,
    p2.product_name as product_2,
    count(*) as times_bought_together,
    round(avg(ov.order_total), 2) as avg_order_value
from product_pairs pp
join order_value ov on ov.order_id = pp.order_id
join public."DimProducts" p1 on p1.product_id = pp.product_1_id
join public."DimProducts" p2 on p2.product_id = pp.product_2_id
group by 1, 2
order by avg_order_value desc;


-- 24. Which product combinations could be recommended as bundles to increase
-- revenue?
with product_pairs as (
    select
        fo1.order_id,
        fo1.product_id as product1,
        fo2.product_id as product2,
        (p1.unit_price * fo1.quantity +
         p2.unit_price * fo2.quantity) as pair_revenue
    from public."FactOrderItems" fo1
    join public."FactOrderItems" fo2
        on fo1.order_id = fo2.order_id
       and fo1.product_id < fo2.product_id
    join public."DimProducts" p1 on p1.product_id = fo1.product_id
    join public."DimProducts" p2 on p2.product_id = fo2.product_id
)
select
    d1.product_name as product_1,
    d2.product_name as product_2,
    count(*) as times_ordered_together,
    round(sum(pair_revenue), 2) as total_pair_revenue
from product_pairs pp
join public."DimProducts" d1 on d1.product_id = pp.product1
join public."DimProducts" d2 on d2.product_id = pp.product2
group by 1,2
order by total_pair_revenue desc
limit 10;


-- 25. Based on product co-occurrence and customer behavior, which products should 
-- UrbanCart promote together to maximize cross-selling opportunities?

with product_pairs as (
    select
        fo1.order_id,
        fo1.product_id as product1,
        fo2.product_id as product2,
        (p1.unit_price * fo1.quantity) +
        (p2.unit_price * fo2.quantity) as pair_revenue
    from public."FactOrderItems" fo1
    join public."FactOrderItems" fo2
        on fo1.order_id = fo2.order_id
       and fo1.product_id < fo2.product_id
    join public."DimProducts" p1 on p1.product_id = fo1.product_id
    join public."DimProducts" p2 on p2.product_id = fo2.product_id
)
select
    dp1.product_name as product_1,
    dp2.product_name as product_2,
    count(*) as times_ordered_together,
    round(sum(pair_revenue), 2) as total_pair_revenue
from product_pairs pp
join public."DimProducts" dp1 on dp1.product_id = pp.product1
join public."DimProducts" dp2 on dp2.product_id = pp.product2
group by 1, 2
order by total_pair_revenue desc, times_ordered_together desc
limit 10;


select * from public."DimProducts"
